controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  robot_state_controller:
    type: robot_state_controller/RobotStateController
    publish_rate: 200

  trigger_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ trigger_joint_motor ]
    velocity:
      joint: trigger_joint
      search_velocity: 9.283
      vel_threshold: 0.1
      pid: { p: 0.7, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }
  cover_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ cover_joint_motor ]
    velocity:
      joint: cover_joint
      search_velocity: -2
      vel_threshold: 0.05
      pid: { p: 0.3, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }

  chassis_controller:
    type: rm_chassis_controllers/OmniController
    # ChassisBase
    publish_rate: 100
    enable_odom_tf: true
    publish_odom_tf: false
    power:
      effort_coeff: 5.0
      vel_coeff: 0.006
      power_offset: -8.41
    twist_angular: 0.5233
    max_odom_vel: 10.0
    timeout: 0.1
    pid_follow: { p: 6.5, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    twist_covariance_diagonal: [ 0.001, 0.001, 0.001, 0.001, 0.001, 0.001 ]

    # OmniController
    wheels:
      left_front:
        pose: [ 0.147, 0.147, 2.356 ]
        joint: left_front_wheel_joint
        <<: &wheel_setting
          roller_angle: 0.
          radius: 0.07625
          pid: { p: 0.25, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
      right_front:
        pose: [ 0.147, -0.147, 0.785 ]
        joint: right_front_wheel_joint
        <<: *wheel_setting
      left_back:
        pose: [ -0.147, 0.147, -2.356 ]
        joint: left_back_wheel_joint
        <<: *wheel_setting
      right_back:
        pose: [ -0.147, -0.147, -0.785 ]
        joint: right_back_wheel_joint
        <<: *wheel_setting

  orientation_controller:
    type: rm_orientation_controller/Controller
    publish_rate: 100
    name: "gimbal_imu"
    frame_source: "odom"
    frame_target: "base_link"

  gimbal_controller:
    type: rm_gimbal_controllers/Controller
    controllers:
      yaw:
        joint: "yaw_joint"
        pid: { p: 0.6, i: 16.0, d: 0.0, i_clamp_max: 0.25, i_clamp_min: -0.25, antiwindup: true, publish_state: true }
        pid_pos: { p: 16.0, i: 0, d: 0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
        chassis_comp_a: 0.01287
        chassis_comp_b: 0.20944
        chassis_comp_c: -1.58123
        chassis_comp_d: 0.02317
        k_v: 1.0
        accel: 28.0
      pitch:
        joint: "pitch_joint"
        pid: { p: 0.7, i: 15.0, d: 0.0, i_clamp_max: 0.1, i_clamp_min: -0.1, antiwindup: true, publish_state: true }
        pid_pos: { p: 25.0, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
        k_v: 1.0
        accel: 40.0
    chassis_vel:
      num_data: 30
      debug: true
    imu_name: "gimbal_imu"
    feedforward:
      gravity: 8.2625
      enable_gravity_compensation: false
      mass_origin: [ 0.006,-0.000093,0.026159 ]
    bullet_solver:
#      resistance_coff_qd_16: 0.001
#      resistance_coff_qd_30: 0.001
#      g: 9.81
#      delay: 0.072
#      dt: 0.001
#      timeout: 0.001
#      min_switch_angle: 2
#      min_switch_count: 8
#      max_track_target_vel: 10.0
#      track_rotate_target_delay: 0.0
#      track_move_target_delay: 0.0
#      gimbal_switch_duration:
#        - [ 50.0,0.0 ]
      resistance_coff_qd_10: 0.001
      resistance_coff_qd_15: 0.001
      resistance_coff_qd_16: 0.001
      resistance_coff_qd_18: 0.001
      resistance_coff_qd_30: 0.001
      g: 9.81
      delay: 0.036
      dt: 0.001
      timeout: 0.001
      publish_rate: 50
      max_switch_angle: 50
      min_switch_angle: 2
      ban_shoot_duration: 0.032
      gimbal_switch_duration: 0.076
      max_track_target_vel: 10.0
      max_chassis_angular_vel: 12.0
      track_rotate_target_delay: 0.042
      track_move_target_delay: 0.04
      wait_next_armor_delay: 0.10
      wait_diagonal_armor_delay: 0.10
      switch_hysteresis: 1.0

  shooter_controller:
    type: rm_shooter_controllers/Controller
    publish_rate: 50
    friction:
      friction_left:
        left_friction_wheel:
          joint: "left_friction_wheel_joint"
          pid: { p: 0.0007, i: 0.005, d: 0.0, i_clamp_max: 0.01, i_clamp_min: -0.01, antiwindup: true, publish_state: true }
      friction_right:
        right_friction_wheel:
          joint: "right_friction_wheel_joint"
          pid: { p: 0.0007, i: 0.005, d: 0.0, i_clamp_max: 0.01, i_clamp_min: -0.01, antiwindup: true, publish_state: true }
          wheel_speed_direction: -1.0
    trigger:
      joint: "trigger_joint"
      pid: { p: 35.0, i: 0.0, d: 1.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true, publish_state: true }
    push_per_rotation: 9
    push_qd_threshold: 0.90
    block_effort: 6.0
    block_speed: 0.1
    block_duration: 0.05
    block_overtime: 0.5
    anti_block_angle: 0.4
    anti_block_threshold: 0.1
    forward_push_threshold: 0.05
    exit_push_threshold: 0.07
    wheel_speed_drop_threshold: 1.4
    wheel_speed_raise_threshold: -1.4
    freq_threshold: 15.0