rm_track:
  max_match_distance: 0.1
  max_target_holding_time: 0.1
  max_storage_time: 1
  max_lost_time: 0.1
  max_new_armor_time: 0.09
  max_judge_period: 0.1
  max_spinning_time: 0.009
  fliter_deque_length: 170
  max_filter_deque_storage_time: 1.
  num_data: 30
  filters:
    - type: height_filter
      basic_range: [ -0.6, 999.0 ]
      double_check_range: [ 0.5, 1.0 ]
    - type: distance_filter
      basic_range: [ 0., 999. ]
      double_check_range: [ 4.0, 6.0 ]
  selectors:
    - last_armor
    - same_id_armor
    - closest_to_image_center
    - new_armor
    - random_armor
  linear_kf:
    Q: [ 9, 9, 9, 9, 9, 9 ]
    R: [ 0.001, 0.001, 0.01 ]
