rm_referee:
  robot_type: engineer
  send_ui_queue_delay: 0.05
  add_ui_frequency: 0.5
  add_ui_max_times: 3
  dbus_topic: "/dbus_data"
  interactive_data:
  ui:
    trigger_change:
      - name: "stone"
        config: { start_position: [ 50, 600 ], size: 15, width: 2, title: "stone:" }
      - name: "gripper"
        config: { start_position: [ 50, 650 ], size: 15, width: 2, title: "gripper:" }
      - name: "servo_mode"
        config: { start_position: [ 50, 700 ], size: 15, width: 2, title: "mode:" }
    fixed:
    flash:
      - name: "engineer_flash_ui"
        data:
          - { flag: 0, config: { type: "line", width: 2, color: "orange",start_position: [ 887, 456 ], end_position: [ 626, 230 ] } }
          - { flag: 0, config: { type: "line", width: 2, color: "orange",start_position: [ 1047, 457 ], end_position: [ 1245, 245 ] } }
    time_change:
      - name: "engineer_joint1"
        config: { type: "line", width: 5, delay: 0.2,
                  start_position: [ 850, 100 ], end_position: [ 850, 300 ] }
        data: { line_length: 100.,  min_val: 0.0025, max_val: 0.45 ,direction: vertical }
      - name: "engineer_joint2"
        config: { type: "line", width: 5, delay: 0.2,
                  start_position: [ 850, 100 ], end_position: [ 950, 200 ] }
        data: { line_length: 80., min_val: -0.0003 , max_val: 0.2626 ,direction: slant }
      - name: "engineer_joint3"
        config: { type: "line", width: 5, delay: 0.2,
                  start_position: [ 850, 100 ], end_position: [ 1100, 100 ] }
        data: { line_length: 100., min_val: 0.005 , max_val: -0.2808 ,direction: horizontal }
